version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./src/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=8000

  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123

  redis:
    image: redis
    volumes:
      - 'redis:/data'

volumes:
  mongodb:
  redis:
