version: '3'

services:
  nginx:
    ports:
      - 80:80

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=prod
    environment:
      - NODE_ENV=prod
      - MONGODB_URL=mongodb://root:password123@mongodb:27017/data-annotation?authSource=admin
    command: bash -c "npm run build && npm start"
