version: '3'

services:
  nginx:
    ports:
      - 8000:80

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test
      - MONGODB_URL=mongodb://root:password123@mongodb:27017/data-annotation-test?authSource=admin
      - REDIS_URL=redis://redis:6379
    command: npm test
    volumes:
      - ./:/app:ro
    container_name: data-annotation-test
    tty: true

  mongodb:
    ports:
      - 27017:27017

  redis:
    ports:
      - 6379:6379
