version: '3'

services:
  nginx:
    ports:
      - 8000:80

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=dev
    environment:
      - NODE_ENV=dev
      - MONGODB_URL=mongodb://root:password123@mongodb:27017/data-annotation-dev?authSource=admin
    command: npm run dev
    volumes:
      - ./:/app
    container_name: data-annotation-dev
