version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./src/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Matkhau123
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
