version: '3'

services:
  nginx:
    ports:
      - 8000:80

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=dev
    environment:
      - NODE_ENV=dev
      - MONGODB_URL=mongodb+srv://pmtri:_tocdoAnhsang123@cluster0.s8xih.mongodb.net/data-annotation-test?retryWrites=true&w=majority
      - REDIS_URL=redis://redis:6379
    command: npm run dev
    volumes:
      - ./:/app
    container_name: data-annotation-dev
    tty: true

  mongodb:
    ports:
      - 27017:27017
